alter table "cicd_BuildStep" add column "typeDetail" text generated always as (type ->> 'detail') stored;
alter table "cicd_BuildStep" add column "typeCategory" text generated always as (type ->> 'category') stored;
alter table "cicd_BuildStep" add column "statusDetail" text generated always as (status ->> 'detail') stored;
alter table "cicd_BuildStep" add column "statusCategory" text generated always as (status ->> 'category') stored;
alter table "cicd_Build" add column "statusDetail" text generated always as (status ->> 'detail') stored;
alter table "cicd_Build" add column "statusCategory" text generated always as (status ->> 'category') stored;
alter table "cicd_Deployment" add column "envDetail" text generated always as (env ->> 'detail') stored;
alter table "cicd_Deployment" add column "envCategory" text generated always as (env ->> 'category') stored;
alter table "cicd_Deployment" add column "statusDetail" text generated always as (status ->> 'detail') stored;
alter table "cicd_Deployment" add column "statusCategory" text generated always as (status ->> 'category') stored;
alter table "cicd_EnvBranchAssociation" add column "environmentDetail" text generated always as (environment ->> 'detail') stored;
alter table "cicd_EnvBranchAssociation" add column "environmentCategory" text generated always as (environment ->> 'category') stored;
alter table "ims_IncidentEvent" add column "typeDetail" text generated always as (type ->> 'detail') stored;
alter table "ims_IncidentEvent" add column "typeCategory" text generated always as (type ->> 'category') stored;
alter table "ims_Incident" add column "severityDetail" text generated always as (severity ->> 'detail') stored;
alter table "ims_Incident" add column "severityCategory" text generated always as (severity ->> 'category') stored;
alter table "ims_Incident" add column "priorityDetail" text generated always as (priority ->> 'detail') stored;
alter table "ims_Incident" add column "priorityCategory" text generated always as (priority ->> 'category') stored;
alter table "ims_Incident" add column "statusDetail" text generated always as (status ->> 'detail') stored;
alter table "ims_Incident" add column "statusCategory" text generated always as (status ->> 'category') stored;
alter table "tms_Epic" add column "statusDetail" text generated always as (status ->> 'detail') stored;
alter table "tms_Epic" add column "statusCategory" text generated always as (status ->> 'category') stored;
alter table "tms_Sprint" add column "stateDetail" text generated always as (state ->> 'detail') stored;
alter table "tms_Sprint" add column "stateCategory" text generated always as (state ->> 'category') stored;
alter table "tms_Task" add column "typeDetail" text generated always as (type ->> 'detail') stored;
alter table "tms_Task" add column "typeCategory" text generated always as (type ->> 'category') stored;
alter table "tms_Task" add column "statusDetail" text generated always as (status ->> 'detail') stored;
alter table "tms_Task" add column "statusCategory" text generated always as (status ->> 'category') stored;
alter table "vcs_Organization" add column "typeDetail" text generated always as (type ->> 'detail') stored;
alter table "vcs_Organization" add column "typeCategory" text generated always as (type ->> 'category') stored;
alter table "vcs_PullRequestReview" add column "stateDetail" text generated always as (state ->> 'detail') stored;
alter table "vcs_PullRequestReview" add column "stateCategory" text generated always as (state ->> 'category') stored;
alter table "vcs_PullRequest" add column "stateDetail" text generated always as (state ->> 'detail') stored;
alter table "vcs_PullRequest" add column "stateCategory" text generated always as (state ->> 'category') stored;
alter table "vcs_PullRequest" add column "linesAdded" integer generated always as (("diffStats" -> 'linesAdded')::integer) stored;
alter table "vcs_PullRequest" add column "linesDeleted" integer generated always as (("diffStats" -> 'linesDeleted')::integer) stored;
alter table "vcs_PullRequest" add column "filesChanged" integer generated always as (("diffStats" -> 'filesChanged')::integer) stored;
alter table "vcs_User" add column "typeDetail" text generated always as (type ->> 'detail') stored;
alter table "vcs_User" add column "typeCategory" text generated always as (type ->> 'category') stored;

-- Mark these columns as 'generated' so that Faros Airbyte Destination will not try to mutate them --
comment on column "cicd_ArtifactCommitAssociation".id is 'generated';
comment on column "cicd_ArtifactDeployment".id is 'generated';
comment on column "cicd_Artifact".id is 'generated';
comment on column "cicd_BuildCommitAssociation".id is 'generated';
comment on column "cicd_BuildStep".id is 'generated';
comment on column "cicd_Build".id is 'generated';
comment on column "cicd_DeploymentChangeset".id is 'generated';
comment on column "cicd_Deployment".id is 'generated';
comment on column "cicd_EnvBranchAssociation".id is 'generated';
comment on column "cicd_Organization".id is 'generated';
comment on column "cicd_Pipeline".id is 'generated';
comment on column "cicd_ReleaseTagAssociation".id is 'generated';
comment on column "cicd_Release".id is 'generated';
comment on column "cicd_Repository".id is 'generated';
comment on column "compute_ApplicationSource".id is 'generated';
comment on column "compute_Application".id is 'generated';
comment on column "ims_IncidentApplicationImpact".id is 'generated';
comment on column "ims_IncidentAssignment".id is 'generated';
comment on column "ims_IncidentEvent".id is 'generated';
comment on column "ims_IncidentTag".id is 'generated';
comment on column "ims_IncidentTasks".id is 'generated';
comment on column "ims_Incident".id is 'generated';
comment on column "ims_Label".id is 'generated';
comment on column "ims_TeamIncidentAssociation".id is 'generated';
comment on column "ims_Team".id is 'generated';
comment on column "ims_User".id is 'generated';
comment on column "tms_Epic".id is 'generated';
comment on column "tms_Label".id is 'generated';
comment on column "tms_ProjectReleaseRelationship".id is 'generated';
comment on column "tms_Project".id is 'generated';
comment on column "tms_Release".id is 'generated';
comment on column "tms_Sprint".id is 'generated';
comment on column "tms_TaskAssignment".id is 'generated';
comment on column "tms_TaskBoardProjectRelationship".id is 'generated';
comment on column "tms_TaskBoardRelationship".id is 'generated';
comment on column "tms_TaskBoard".id is 'generated';
comment on column "tms_TaskDependency".id is 'generated';
comment on column "tms_TaskProjectRelationship".id is 'generated';
comment on column "tms_TaskPullRequestAssociation".id is 'generated';
comment on column "tms_TaskReleaseRelationship".id is 'generated';
comment on column "tms_TaskTag".id is 'generated';
comment on column "tms_Task".id is 'generated';
comment on column "tms_User".id is 'generated';
comment on column "vcs_BranchCommitAssociation".id is 'generated';
comment on column "vcs_Branch".id is 'generated';
comment on column "vcs_Commit".id is 'generated';
comment on column "vcs_Membership".id is 'generated';
comment on column "vcs_Organization".id is 'generated';
comment on column "vcs_PullRequestComment".id is 'generated';
comment on column "vcs_PullRequestReview".id is 'generated';
comment on column "vcs_PullRequest".id is 'generated';
comment on column "vcs_Repository".id is 'generated';
comment on column "vcs_Tag".id is 'generated';
comment on column "vcs_User".id is 'generated';

comment on column "cicd_BuildStep"."typeDetail" is 'generated';
comment on column "cicd_BuildStep"."typeCategory" is 'generated';
comment on column "cicd_BuildStep"."statusDetail" is 'generated';
comment on column "cicd_BuildStep"."statusCategory" is 'generated';
comment on column "cicd_Build"."statusDetail" is 'generated';
comment on column "cicd_Build"."statusCategory" is 'generated';
comment on column "cicd_Deployment"."envDetail" is 'generated';
comment on column "cicd_Deployment"."envCategory" is 'generated';
comment on column "cicd_Deployment"."statusDetail" is 'generated';
comment on column "cicd_Deployment"."statusCategory" is 'generated';
comment on column "cicd_EnvBranchAssociation"."environmentDetail" is 'generated';
comment on column "cicd_EnvBranchAssociation"."environmentCategory" is 'generated';
comment on column "ims_IncidentEvent"."typeDetail" is 'generated';
comment on column "ims_IncidentEvent"."typeCategory" is 'generated';
comment on column "ims_Incident"."severityDetail" is 'generated';
comment on column "ims_Incident"."severityCategory" is 'generated';
comment on column "ims_Incident"."priorityDetail" is 'generated';
comment on column "ims_Incident"."priorityCategory" is 'generated';
comment on column "ims_Incident"."statusDetail" is 'generated';
comment on column "ims_Incident"."statusCategory" is 'generated';
comment on column "tms_Epic"."statusDetail" is 'generated';
comment on column "tms_Epic"."statusCategory" is 'generated';
comment on column "tms_Sprint"."stateDetail" is 'generated';
comment on column "tms_Sprint"."stateCategory" is 'generated';
comment on column "tms_Task"."typeDetail" is 'generated';
comment on column "tms_Task"."typeCategory" is 'generated';
comment on column "tms_Task"."statusDetail" is 'generated';
comment on column "tms_Task"."statusCategory" is 'generated';
comment on column "vcs_Organization"."typeDetail" is 'generated';
comment on column "vcs_Organization"."typeCategory" is 'generated';
comment on column "vcs_PullRequestReview"."stateDetail" is 'generated';
comment on column "vcs_PullRequestReview"."stateCategory" is 'generated';
comment on column "vcs_PullRequest"."stateDetail" is 'generated';
comment on column "vcs_PullRequest"."stateCategory" is 'generated';
comment on column "vcs_PullRequest"."linesAdded" is 'generated';
comment on column "vcs_PullRequest"."linesDeleted" is 'generated';
comment on column "vcs_PullRequest"."filesChanged" is 'generated';
comment on column "vcs_User"."typeDetail" is 'generated';
comment on column "vcs_User"."typeCategory" is 'generated';
