create index "ims_Alert_origin_idx" on "ims_Alert"(origin);
create index "ims_Alert_uid_idx" on "ims_Alert"(uid);
create index "ims_Alert_title_idx" on "ims_Alert"(title);
create index "ims_Alert_alertsource_idx" on "ims_Alert"("alertsouce");
create index "ims_Alert_alertowner_idx" on "ims_Alert"("alertowner");
create index "ims_Alert_priority_idx" on "ims_Alert" using gin(priority);
create index "ims_Alert_status_idx" on "ims_Alert" using gin(status);
create index "ims_Alert_createdAt_idx" on "ims_Alert"("createdAt");
create index "ims_Alert_updatedAt_idx" on "ims_Alert"("updatedAt");
create index "ims_Alert_lastOccurredAt_idx" on "ims_Alert"("lastOccurredAt");
create index "ims_Alert_source_idx" on "ims_Alert"(source);
create index "ims_AlertAssignment_origin_idx" on "ims_AlertAssignment"(origin);
create index "ims_AlertAssignment_alert_idx" on "ims_AlertAssignment"(alert);
create index "ims_AlertAssignment_assignee_idx" on "ims_AlertAssignment"(assignee);
create index "ims_AlertTag_origin_idx" on "ims_AlertTag"(origin);
create index "ims_AlertTag_alert_idx" on "ims_AlertTag"(alert);
create index "ims_AlertTag_label_idx" on "ims_AlertTag"(label);
create index "ims_AlertIntegrationAssociation_origin_idx" on "ims_AlertIntegrationAssociation"(origin);
create index "ims_AlertIntegrationAssociation_uid_idx" on "ims_AlertIntegrationAssociation"(uid);
create index "ims_AlertIntegrationAssociation_type_idx" on "ims_AlertIntegrationAssociation" using gin(type);
create index "ims_AlertIntegrationAssociation_createdAt_idx" on "ims_AlertIntegrationAssociation"("createdAt");
create index "ims_AlertIntegrationAssociation_detail_idx" on "ims_AlertIntegrationAssociation"(detail);
create index "ims_AlertIntegrationAssociation_alert_idx" on "ims_AlertIntegrationAssociation"(alert);
create index "ims_AlertReportAssociation_origin_idx" on "ims_AlertReportAssociation"(origin);
create index "ims_AlertReportAssociation_report_idx" on "ims_AlertReportAssociation" using gin(report);
create index "ims_AlertReportAssociation_createdAt_idx" on "ims_AlertReportAssociation"("createdAt");
create index "ims_AlertReportAssociation_detail_idx" on "ims_AlertReportAssociation"(detail);
create index "ims_AlertReportAssociation_alert_idx" on "ims_AlertReportAssociation"(alert);
create index "ims_AlertSourceAssociation_origin_idx" on "ims_AlertSourceAssociation"(origin);
create index "ims_AlertSourceAssociation_source_idx" on "ims_AlertSourceAssociation"(source);
create index "ims_AlertSourceAssociation_alert_idx" on "ims_AlertSourceAssociation"(alert);
create index "ims_TeamAlertAssociation_origin_idx" on "ims_TeamAlertAssociation"(origin);
create index "ims_TeamAlertAssociation_alert_idx" on "ims_TeamAlertAssociation"(alert);
create index "ims_TeamAlertAssociation_team_idx" on "ims_TeamAlertAssociation"(team);
