apiVersion: v1
kind: Service
metadata:
  name: airbyte-server-svc
  labels:
    app.kubernetes.io/name: airbyte-server
    app.kubernetes.io/component: server
spec:
  selector:
    app.kubernetes.io/name: airbyte-server
    app.kubernetes.io/component: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-server
  labels:
    app.kubernetes.io/name: airbyte-server
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: airbyte-server
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: airbyte-server
        app.kubernetes.io/component: server
