version: "3.7"
x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file
services:
  faros-init:
    image: farosai/faros-ce-init:latest
    container_name: faros-init
    # 3 retries on failure
    #restart: on-failure:3
    restart: "no"
    entrypoint: /bin/sh -c "/flyway/faros/scripts/entrypoint.sh && tail -f /dev/null"
    depends_on:
      - faros-db
    environment:
      AIRBYTE_API_CALLS_CONCURRENCY:
      AIRBYTE_DESTINATION_HASURA_URL: "http://localhost:8080"
      AIRBYTE_FORCE_SETUP: false
      AIRBYTE_URL: "http://airbyte-webapp:80"
      FAROS_EMAIL:
      FAROS_INIT_VERSION:
      FAROS_START_SOURCE:
      HASURA_URL: "http://hasura:8080"
      LOG_LEVEL: "info"
      METABASE_FAROS_DB_HOST: "faros-db"
      METABASE_PASSWORD: "admin"
      METABASE_URL: "http://metabase:3000"
      METABASE_USER: "admin@admin.com"
      METABASE_USE_SSL: false
      FAROS_DB_NAME: "faros"
      FAROS_DB_HOST: "faros-db"
      FAROS_DB_PORT: 5432
      FAROS_DB_USER: "docker"
      FAROS_DB_PASSWORD: "docker"
      FAROS_CONFIG_DB_HOST: "faros-db"
      FAROS_CONFIG_DB_PORT: 5432
      FAROS_CONFIG_DB_USER: "docker"
      FAROS_CONFIG_DB_PASSWORD: "docker"
      HASURA_GRAPHQL_DATABASE_URL:
      HASURA_DB_NAME: "hasura"
      HASURA_GRAPHQL_ADMIN_SECRET: "admin"
      METABASE_DB_NAME: "metabase"
      N8N_DB_NAME: "n8n"
    healthcheck:
      test: ["CMD", "psql", "-d", "postgres://docker:docker@faros-db:5432/n8n", "-c", "SELECT 1"]
      interval: 5s
      timeout: 2s
      start_period: 10s
      retries: 5
  
  init:
    image: airbyte/init:0.40.9
    logging: *default-logging
    container_name: init
    restart: "no"
    depends_on:
      - faros-db
    command: /bin/sh -c "./scripts/create_mount_directories.sh /local_parent /tmp /tmp/airbyte_local && tail -f /dev/null"
    environment:
      - LOCAL_ROOT=/tmp/airbyte_local
      - HACK_LOCAL_ROOT_PARENT=/tmp
    volumes:
      - tmp:/local_parent
  bootloader:
    image: airbyte/bootloader:0.40.9
    logging: *default-logging
    container_name: airbyte-bootloader
    restart: "no"
    depends_on:
      - faros-db
    entrypoint: /bin/sh -c "airbyte-bootloader-0.40.9/bin/airbyte-bootloader && tail -f /dev/null"
    environment:
      - AIRBYTE_VERSION=0.40.9
      - CONFIG_DATABASE_PASSWORD=
      - CONFIG_DATABASE_URL=
      - CONFIG_DATABASE_USER=
      - DATABASE_PASSWORD=docker
      - DATABASE_URL=jdbc:postgresql://faros-db:5432/airbyte
      - DATABASE_USER=docker
      - LOG_LEVEL=INFO
      - RUN_DATABASE_MIGRATION_ON_STARTUP=true
  faros-db:
    image: airbyte/db:0.40.9
    logging: *default-logging
    container_name: airbyte-db
    restart: unless-stopped
    environment:
      - CONFIG_DATABASE_PASSWORD=
      - CONFIG_DATABASE_URL=
      - CONFIG_DATABASE_USER=
      - DATABASE_PASSWORD=docker
      - DATABASE_URL=jdbc:postgresql://faros-db:5432/airbyte
      - DATABASE_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  worker:
    image: airbyte/worker:0.40.9
    logging: *default-logging
    container_name: airbyte-worker
    restart: unless-stopped
    depends_on:
      - faros-db
    environment:
      - AIRBYTE_VERSION=0.40.9
      - AUTO_DISABLE_FAILING_CONNECTIONS=false
      - CONFIG_DATABASE_PASSWORD=
      - CONFIG_DATABASE_URL=
      - CONFIG_DATABASE_USER=
      - CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=0.35.15.001
      - CONFIG_ROOT=/data
      - DATABASE_PASSWORD=docker
      - DATABASE_URL=jdbc:postgresql://faros-db:5432/airbyte
      - DATABASE_USER=docker
      - DEPLOYMENT_MODE=
      - INTERNAL_API_HOST=airbyte-server:8001
      - JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=0.29.15.001
      - JOB_MAIN_CONTAINER_CPU_LIMIT
      - JOB_MAIN_CONTAINER_CPU_REQUEST
      - JOB_MAIN_CONTAINER_MEMORY_LIMIT
      - JOB_MAIN_CONTAINER_MEMORY_REQUEST
      - LOCAL_DOCKER_MOUNT=/tmp/airbyte_local
      - LOCAL_ROOT=/tmp/airbyte_local
      - LOG_LEVEL=INFO
      - LOG_CONNECTOR_MESSAGES=
      - MAX_CHECK_WORKERS=5
      - MAX_DISCOVER_WORKERS=5
      - MAX_SPEC_WORKERS=5
      - MAX_SYNC_WORKERS=5
      - NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_LIMIT=
      - NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_REQUEST=
      - NORMALIZATION_JOB_MAIN_CONTAINER_CPU_LIMIT=
      - NORMALIZATION_JOB_MAIN_CONTAINER_CPU_REQUEST=
      - SECRET_PERSISTENCE=NONE
      - SYNC_JOB_MAX_ATTEMPTS=1
      - SYNC_JOB_MAX_TIMEOUT_DAYS=1
      - TEMPORAL_HOST=airbyte-temporal:7233
      - TRACKING_STRATEGY=logging
      - WEBAPP_URL=http://localhost:8000/
      - WORKER_ENVIRONMENT=docker
      - WORKSPACE_DOCKER_MOUNT=airbyte_workspace
      - WORKSPACE_ROOT=/tmp/workspace
      - METRIC_CLIENT=
      - OTEL_COLLECTOR_ENDPOINT="http://host.docker.internal:4317"
      - JOB_ERROR_REPORTING_STRATEGY=logging
      - JOB_ERROR_REPORTING_SENTRY_DSN=
      - ACTIVITY_MAX_ATTEMPT=
      - ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS=
      - ACTIVITY_MAX_DELAY_BETWEEN_ATTEMPTS_SECONDS=
      - WORKFLOW_FAILURE_RESTART_DELAY_SECONDS=
      - USE_STREAM_CAPABLE_STATE=true
      - MICRONAUT_ENVIRONMENTS=control
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/tmp/workspace
      - tmp:/tmp/airbyte_local
    ports:
      - 9000:9000
  server:
    image: airbyte/server:0.40.9
    logging: *default-logging
    container_name: airbyte-server
    depends_on:
      - faros-db
    restart: unless-stopped
    environment:
      - AIRBYTE_ROLE=
      - AIRBYTE_VERSION=0.40.9
      - CONFIG_DATABASE_PASSWORD=
      - CONFIG_DATABASE_URL=
      - CONFIG_DATABASE_USER=
      - CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=0.35.15.001
      - CONFIG_ROOT=/data
      - DATABASE_PASSWORD=docker
      - DATABASE_URL=jdbc:postgresql://faros-db:5432/airbyte
      - DATABASE_USER=docker
      - JOB_MAIN_CONTAINER_CPU_LIMIT=
      - JOB_MAIN_CONTAINER_CPU_REQUEST=
      - JOB_MAIN_CONTAINER_MEMORY_LIMIT=
      - JOB_MAIN_CONTAINER_MEMORY_REQUEST=
      - JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=0.29.15.001
      - LOG_LEVEL=INFO
      - NEW_SCHEDULER=
      - SECRET_PERSISTENCE=NONE
      - TEMPORAL_HOST=airbyte-temporal:7233
      - TRACKING_STRATEGY=logging
      - JOB_ERROR_REPORTING_STRATEGY=
      - JOB_ERROR_REPORTING_SENTRY_DSN=
      - WEBAPP_URL=http://localhost:8000/
      - WORKER_ENVIRONMENT=docker
      - WORKSPACE_ROOT=/tmp/workspace
    ports:
      - 8001:8001
    volumes:
      - workspace:/tmp/workspace
      - data:/data
      - tmp:/tmp/airbyte_local
  webapp:
    image: airbyte/webapp:0.40.9
    logging: *default-logging
    container_name: airbyte-webapp
    restart: unless-stopped
    ports:
      - 8000:80
    environment:
      - AIRBYTE_ROLE=
      - AIRBYTE_VERSION=0.40.9
      - API_URL=/api/v1/
      - INTERNAL_API_HOST=airbyte-server:8001
      - OPENREPLAY=
      - PAPERCUPS_STORYTIME=disabled
      - TRACKING_STRATEGY=logging
    depends_on:
      - faros-db
      - server
      - worker
      - airbyte-temporal
  airbyte-temporal:
    image: airbyte/temporal:0.40.9
    logging: *default-logging
    container_name: airbyte-temporal
    restart: unless-stopped
    ports:
      - 7233:7233
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - LOG_LEVEL=INFO
      - POSTGRES_PWD=docker
      - POSTGRES_SEEDS=faros-db
      - POSTGRES_USER=docker
    volumes:
      - tmp:/etc/temporal/config/dynamicconfig
  airbyte-cron:
    image: airbyte/cron:0.40.9
    logging: *default-logging
    container_name: airbyte-cron
    restart: unless-stopped
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - LOG_LEVEL=INFO
      - POSTGRES_PWD=docker
      - POSTGRES_SEEDS=faros-db
      - POSTGRES_USER=docker
      - TEMPORAL_HISTORY_RETENTION_IN_DAYS=
      - WORKSPACE_ROOT=/tmp/workspace
    volumes:
      - workspace:/tmp/workspace
  
  # Other services
  hasura:
    image: hasura/graphql-engine:v2.1.1
    container_name: hasura
    ports:
      - 8080:8080
    depends_on:
      faros-init:
          condition: service_healthy
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "admin"
      HASURA_GRAPHQL_DATABASE_URL: postgres://docker:docker@faros-db:5432/faros
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://docker:docker@faros-db:5432/hasura
  metabase:
    image: farosai.docker.scarf.sh/farosai/metabase-m1:v0.45.2.1
    container_name: metabase
    ports:
      - 3000:3000
    depends_on:
      faros-init:
          condition: service_healthy
    restart: unless-stopped
    environment:
      MB_ANON_TRACKING_ENABLED: "false"
      MB_DB_DBNAME: "metabase"
      MB_DB_HOST: "faros-db"
      MB_DB_PASS: "docker"
      MB_DB_PORT: 5432
      MB_DB_TYPE: postgres
      MB_DB_USER: "docker"
      MB_PASSWORD_COMPLEXITY: weak
      MB_PASSWORD_LENGTH: 1
      MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE: "false"
  n8n:
    image: n8nio/n8n:0.164.1
    container_name: n8n
    ports:
      - 5678:5678
    depends_on:
      faros-init:
          condition: service_healthy
    restart: unless-stopped
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: "faros-db"
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_USER: "docker"
      DB_POSTGRESDB_PASSWORD: "docker"
      N8N_PERSONALIZATION_ENABLED: "false"
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
    volumes:
      - n8n:/home/node/

volumes:
  workspace:
    name: airbyte_workspace
  data:
    name: airbyte_data
  db:
    name: airbyte_db
  n8n:
    name: n8n_data
  tmp:
    name: tmp
