mutation insert_cicd_Organization(
  $data_run_organization: String!
  $data_run_source: String
  $data_origin: String
) {
  insert_cicd_Organization_one(
    object: {
      uid: $data_run_organization
      source: $data_run_source
      origin: $data_origin
    }
    on_conflict: {
      constraint: cicd_Organization_pkey
      update_columns: [
        origin
        refreshedAt
      ]
    }
  ) {
    id
  }
}
