mutation insert_cicd_ArtifactDeployment(
  $data_artifact_id: String!
  $data_artifact_organization: String!
  $data_artifact_repository: String!
  $data_artifact_source: String!
  $data_deploy_id: String!
  $data_deploy_source: String!
  $data_origin: String
) {
  insert_cicd_ArtifactDeployment_one(
    object: {
      cicd_Deployment: {
        data: {
          uid: $data_deploy_id
          source: $data_deploy_source
          origin: $data_origin
        }
        on_conflict: {
          constraint: cicd_Deployment_pkey
          update_columns: refreshedAt
        }
      }
      cicd_Artifact: {
        data: {
          uid: $data_artifact_id
          cicd_Repository: {
            data: {
              uid: $data_artifact_repository
              cicd_Organization: {
                data: {
                  uid: $data_artifact_organization
                  source: $data_artifact_source
                  origin: $data_origin
                }
                on_conflict: {
                  constraint: cicd_Organization_pkey
                  update_columns: refreshedAt
                }
              }
              origin: $data_origin
            }
            on_conflict: {
              constraint: cicd_Repository_pkey
              update_columns: refreshedAt
            }
          }
          origin: $data_origin
        }
        on_conflict: {
          constraint: cicd_Artifact_pkey
          update_columns: refreshedAt
        }
      }
      origin: $data_origin
    }
    on_conflict: {
      constraint: cicd_ArtifactDeployment_pkey
      update_columns: [
        origin
        refreshedAt
      ]
    }
  ) {
    id
  }
}
