mutation insert_compute_Application_one(
  $uid: String!
  $name: String!
  $platform: String!
  $data_origin: String
) {
  insert_compute_Application_one(
    object: {
      uid: $uid
      name: $name
      platform: $platform
      origin: $data_origin
    }
    on_conflict: {
      constraint: compute_Application_pkey
      update_columns: [
        name
        platform
        origin
        refreshedAt
      ]
    }
  ) {
    uid
    id
  }
}
