mutation insert_faros_metric_definition(
  $data_uid: String!
  $data_name: String!
  $data_origin: String
) {
  insert_faros_MetricDefinition_one(
    object: {
      uid: $data_uid
      name: $data_name
      origin: $data_origin
    }
    on_conflict: {
      constraint: faros_MetricDefinition_pkey
      update_columns: [
        origin
        refreshedAt
      ]
    }
  ) {
    id
  }
}
