mutation insert_vcs_PullRequestCommit(
  $data_commit_organization: String!
  $data_commit_repository: String!
  $data_commit_sha: String!
  $data_commit_source: String!
  $data_pull_request_uid: String!
  $data_pull_request_number: Int!
  $data_origin: String!
) {
  insert_vcs_PullRequestCommit_one(
    object: {
      vcs_Commit: {
        data: {
          uid: $data_commit_sha
          vcs_Repository: {
            data: {
              uid: $data_commit_repository
              vcs_Organization: {
                data: {
                  uid: $data_commit_organization
                  source: $data_commit_source
                  origin: $data_origin
                }
                on_conflict: {
                  constraint: vcs_Organization_pkey
                  update_columns: refreshedAt
                }
              }
              origin: $data_origin
            }
            on_conflict: {
              constraint: vcs_Repository_pkey
              update_columns: refreshedAt
            }
          }
        }
        on_conflict: {constraint: vcs_Commit_pkey, update_columns: refreshedAt}
      }
      vcs_PullRequest: {
        data: {
          origin: $data_origin
          uid: $data_pull_request_uid
          number: $data_pull_request_number
          vcs_Repository: {
            data: {
              uid: $data_commit_repository
              vcs_Organization: {
                data: {
                  uid: $data_commit_organization
                  source: $data_commit_source
                  origin: $data_origin
                }
                on_conflict: {
                  constraint: vcs_Organization_pkey
                  update_columns: refreshedAt
                }
              }
              origin: $data_origin
            }
            on_conflict: {
              constraint: vcs_Repository_pkey
              update_columns: refreshedAt
            }
          }
        }
        on_conflict: {
          constraint: vcs_PullRequest_pkey
          update_columns: refreshedAt
        }
      }
      origin: $data_origin
    }
    on_conflict: {
      constraint: vcs_PullRequestCommit_pkey
      update_columns: [
        origin
        refreshedAt
      ]
    }
  ) {
    id
  }
}

