name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]
permissions:
  contents: read
  pull-requests: write
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: contributor-assistant/github-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_BOT_GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures/v1/cla.json'
          path-to-document: 'https://docs.faros.ai/docs/individual-cla' 
          # branch should not be protected
          branch: 'main'
          allowlist: cjwooo,tovbinm,thomas-gerber,ypc-faros

         #below are the optional inputs - If the optional inputs are not given, then default values will be taken
          remote-organization-name: faros-ai
          remote-repository-name: cla
          create-file-commit-message: 'Creating/updating file for storing CLA Signatures'
          signed-commit-message: '$contributorName has signed the CLA in #$pullRequestNo'
          custom-notsigned-prcomment: 'Thank you for your submission, we really appreciate it. Faros can accept contrbutions only from authors who accepted and signed [Contributor License Agreement](https://docs.faros.ai/docs/individual-cla). Please kindly read it and accept by posting the following comment on this PR:'
          custom-pr-sign-comment: 'I have read the CLA Document and I hereby sign the CLA'
          #custom-allsigned-prcomment: 'pull request comment when all contributors has signed, defaults to **CLA Assistant Lite bot** All Contributors have signed the CLA.'
          lock-pullrequest-aftermerge: true
