name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Start services
        run: docker-compose up --quiet-pull -d

      # TODO: do some actual testing
      - name: Run tests
        run: sleep 30s
        shell: bash

      - name: Show logs
        run: docker-compose logs --tail all

      - name: Show services
        run: docker-compose ps -a

      - name: Stop services
        run: docker-compose down
