name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build
        run: npm ci --unsafe-perm
        working-directory: init

      - name: Docker Compose version
        run: docker-compose version --short

      - name: Start services
        run: docker-compose up --quiet-pull -d

      - name: Run tests
        run: npm test -- --coverage
        working-directory: init

      - name: Show logs
        run: docker-compose logs --tail all

      - name: Show services
        run: docker-compose ps -a

      - name: Stop services
        run: docker-compose down
