kind: Service
apiVersion: v1
metadata:
  name: metabase
  labels:
    app.kubernetes.io/name: metabase
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: metabase
  ports:
    - name: http
      port: 80
      targetPort: http
